### ISSUE TITLE
Can't exclude user node fields "id" and "pk"

### ISSUE THREAD

**Issue by pors** [PedroBern/django-graphql-auth#24]
I have this setting:

`"USER_NODE_EXCLUDE_FIELDS": ["password", "is_superuser", "id", "pk"]`

And I get this warning:

```
.../graphene_django/types.py:103: UserWarning: Excluding the custom field "id" on DjangoObjectType "UserNode" has no effect. Either remove the custom field or remove the field from the "exclude" list.
```

And the same for `pk`.

**Comment by PedroBern** [comment]
> **I'm not sure, but my first hunch is:**

## pk
Because it is a field in the [UserNode](https://github.com/PedroBern/django-graphql-auth/blob/master/graphql_auth/schema.py#L10), I didn't try, but probably trying to exclude archived/verified/secondary_email would result in the same warning

## id
Because of `graphene.relay.Node.Field` that has an `id` field, resulting in the same case I wrote above for pk.

---

Being these cases, I don't plan to fix it, but I will investigate further to see if I find other possible reasons. If you make progress on this please let me know!

**Comment by pors** [comment]
What is the reason you chose for the relay interface for users?

**Comment by PedroBern** [comment]
Because of the [filtering](https://docs.graphene-python.org/projects/django/en/latest/filtering/#filtering). From the docs:

> (...) filtering is automatically available when implementing a relay.Node. (...)

**Comment by PedroBern** [comment]
It's odd, when I try to remove the `id` I don't get the warning message. When I try to remove the `pk` I get an exception:

```
Exception: "pk" exists on model <class 'users.models.CustomUser'> but it's not a field.
```

What version are you using of `django-graphql-auth` and `graphene`?

**Comment by pors** [comment]
> It's odd, when I try to remove the `id` I don't get the warning message. When I try to remove the `pk` I get an exception:
> 

Removing how?

> ```
> Exception: "pk" exists on model <class 'users.models.CustomUser'> but it's not a field.
> ```
> 
> What version are you using of `django-graphql-auth` and `graphene`?

```
graphene==2.1.8
graphene-django==2.9.0
django-graphql-auth==0.3.8
```

**Comment by PedroBern** [comment]
> Removing how?
I mean, adding to `USER_NODE_EXCLUDE_FIELDS `.

**Comment by pors** [comment]
Shall I close this? Now that we have #27 coming up?

**Comment by PedroBern** [comment]
yes, I close it
