### ISSUE TITLE
Help using AbstractBaseUser

### ISSUE THREAD

**Issue by feroz39** [PedroBern/django-graphql-auth#42]
I want to overwrite the original django user model to custom user model with AbstractBaseUser. So, I can remove firstname, lastname etc field from the model. But it cause error like 'Unknown field(s)'. Are there any way to use AbstractBaseUser instead of AbstractUser for custom user with django-graphql-auth?

**Comment by PedroBern** [comment]
Hi @feroz, it's not an error since you need to provide the fields for `AbstractBaseUser`. You can do this, but just make sure what is used in `django-graphql-auth` is present in your model, it is probably only the `USERNAME_FIELD`, `EMAIL_FIELD` and `is_active`. Also you need to update these settings: `LOGIN_ALLOWED_FIELDS` and `REGISTER_MUTATION_FIELDS` if you change the `username` and `email` fields name, and update `UPDATE_MUTATION_FIELDS` if you remove the `first_name` and `last_name`. 

If you have any problems with it, please provide some code so maybe I can help.
