### ISSUE TITLE
Custom user model without username error with REGISTER_MUTATION_FIELDS

### ISSUE THREAD

**Issue by bzhr** [PedroBern/django-graphql-auth#9]
This app does not have username, but filling the first and last name is obligatory. 
In `settings.py` I have:
```
GRAPHQL_AUTH = {
    'LOGIN_ALLOWED_FIELDS': ['email'],
    'REGISTER_MUTATION_FIELDS': ['email', 'first_name', 'last_name'],
    'REGISTER_MUTATION_FIELDS_OPTIONAL': [],
}
```

Graphql relay register mutation:
```
mutation {
  register(
    input: {
      email: "test3@email.com",
      firstName: "Test3",
      lastName: "Last",
      password1: "supersecretpassword",
      password2: "supersecretpassword"
    }
  ) {
    success,
    errors,
    token,
    refreshToken
  }
}
```
Response:
```
{
  "errors": [
    {
      "message": "Please, enter valid credentials",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "register"
      ]
    }
  ],
  "data": {
    "register": null
  }
}
```

Error from python console:
```
File "/home/bozho/.local/share/virtualenvs/server-WyGHa9Al/lib/python3.7/site-packages/graphql_jwt/decorators.py", line 91, in wrapper
    _('Please, enter valid credentials'))
graphql.error.located_error.GraphQLLocatedError: Please, enter valid credentials
```

Before the error the email is sent to the user. The user, however, is not created. 
This can be either something improperly configured by me, or an error in the library.

**Comment by PedroBern** [comment]
As you can see in the error:

> File "(...)site-packages/**graphql_jwt**/decorators.py", line 91, (...)

This is a `graphql_jwt` error, not from `graphql_auth`. It's simple how the `graphql_jwt` works, your custom user model probably does not have a `USERNAME_FIELD` set.

You can simple set it by adding the following to your model:

```python
USERNAME_FIELD = "email"
```

Please try it, if does not work, I will try to reproduce the error for further investigation.

> Before the error the email is sent to the user. The user, however, is not created.
This can be either something improperly configured by me, or an error in the library.

It can be improved, currently this lib creates the `User`, `UserStatus`, send the email and login  inside a atomic transaction on the [register mixin](https://github.com/PedroBern/django-graphql-auth/blob/da09bf9fd73bbbe73eb42db84ec7cb7b1a2d443d/graphql_auth/mixins.py#L38), since the error was in the login, it did cancel the transaction, but the email was already send.

Also currently the documentation does not talk about custom user and the need for the `USERNAME_FIELD`, it also can be improved.

I will be waiting your response to see if now it is working.

**Comment by bzhr** [comment]
Thank you for your answer. I didn't use a custom User model and that has been the cause of the error. Creating a custom User model with `USERNAME_FIELD = "email"` solved the error.

**Comment by PedroBern** [comment]
You also should add the `EMAIL_FIELD`:

```python
USERNAME_FIELD = "email"
EMAIL_FIELD = "email"
```
